In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization, LayerNormalization

In [2]:
np.random.seed(42)

data = np.random.randint(1, 20, size=(4, 5)).astype(np.float32)

print("Original Input Values:")
print(data)

Original Input Values:
[[ 7. 15. 11.  8.  7.]
 [19. 11. 11.  4.  8.]
 [ 3.  2. 12.  6.  2.]
 [ 1. 12. 12. 17. 10.]]


In [3]:
batch_norm = BatchNormalization()

batch_output = batch_norm(data, training=True)

print("Batch Normalization Output:")
print(batch_output.numpy())

Batch Normalization Output:
[[-0.07161081  1.0313995  -0.9980049  -0.15094328  0.08481407]
 [ 1.6470473   0.20628    -0.9980049  -0.95597434  0.42407012]
 [-0.6444968  -1.6502388   0.9980068  -0.5534588  -1.6114662 ]
 [-0.9309398   0.41255975  0.9980068   1.6603765   1.1025822 ]]


In [4]:
training=True

In [5]:
layer_norm = LayerNormalization()

layer_output = layer_norm(data)

print("Layer Normalization Output:")
print(layer_output.numpy())

Layer Normalization Output:
[[-0.84618306  1.7574568   0.45563698 -0.5207281  -0.84618306]
 [ 1.7060983   0.0812428   0.0812428  -1.3405058  -0.5280781 ]
 [-0.527028   -0.790542    1.8445978   0.26351392 -0.790542  ]
 [-1.7944356   0.30543602  0.30543602  1.2599231  -0.07635891]]
